/**:
  ros__parameters:
    dir_logs: "Projects/testing"
    dirs_sub:
      - "flir"
    names_actors:
      - "flir1"
      - "flir2"
    topics:
      - "/mess2/flir1/image_raw"
      - "/mess2/flir2/image_raw"